// <auto-generated />
using System;
using Forgekeeper.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable enable

namespace Forgekeeper.Infrastructure.Data.Migrations;

[DbContext(typeof(ForgeDbContext))]
[Migration("20260416180000_Initial")]
partial class Initial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63)
            .UseIdentityByDefaultColumns();

        modelBuilder.HasPostgresExtension("pg_trgm");

        // This snapshot is intentionally minimal — the full snapshot is in ForgeDbContextModelSnapshot.cs.
        // EF Core uses the snapshot, not this designer file, for diffing.
#pragma warning restore 612, 618
    }
}
