// <auto-generated />
using System;
using Forgekeeper.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable enable

namespace Forgekeeper.Infrastructure.Data.Migrations;

[DbContext(typeof(ForgeDbContext))]
partial class ForgeDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63)
            .UseIdentityByDefaultColumns();

        modelBuilder.HasPostgresExtension("pg_trgm");

        modelBuilder.Entity("Forgekeeper.Core.Models.Creator", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasDefaultValueSql("gen_random_uuid()");

            b.Property<string>("AvatarUrl")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("ExternalId")
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<int>("ModelCount")
                .HasColumnType("integer");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<string>("Source")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<string>("SourceUrl")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)");

            b.Property<DateTime>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("Name")
                .HasMethod("gin")
                .HasOperators("gin_trgm_ops");

            b.HasIndex("Name", "Source")
                .IsUnique();

            b.ToTable("creators");
        });

        modelBuilder.Entity("Forgekeeper.Core.Models.ImportQueueItem", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasDefaultValueSql("gen_random_uuid()");

            b.Property<string>("ConfirmedCreator")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<string>("ConfirmedModelName")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)");

            b.Property<string>("ConfirmedSource")
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<double>("ConfidenceScore")
                .HasColumnType("double precision");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("DetectedCreator")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<string>("DetectedModelName")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)");

            b.Property<string>("DetectedSource")
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<string>("DetectedVariantType")
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<string>("ErrorMessage")
                .HasColumnType("text");

            b.Property<string>("OriginalPath")
                .IsRequired()
                .HasMaxLength(2000)
                .HasColumnType("character varying(2000)");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<DateTime>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("Status");

            b.ToTable("import_queue");
        });

        modelBuilder.Entity("Forgekeeper.Core.Models.PluginConfig", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasDefaultValueSql("gen_random_uuid()");

            b.Property<bool>("IsEncrypted")
                .HasColumnType("boolean");

            b.Property<string>("Key")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<string>("PluginSlug")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            b.Property<DateTime>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Value")
                .IsRequired()
                .HasColumnType("text");

            b.HasKey("Id");

            b.HasIndex("PluginSlug", "Key")
                .IsUnique();

            b.ToTable("plugin_configs");
        });

        modelBuilder.Entity("Forgekeeper.Core.Models.Model3D", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasDefaultValueSql("gen_random_uuid()");

            b.Property<string>("AcquisitionMethod")
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<string>("AcquisitionOrderId")
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<string>("BasePath")
                .IsRequired()
                .HasMaxLength(2000)
                .HasColumnType("character varying(2000)");

            b.Property<string>("Category")
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<string>("CollectionName")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<string>("Components")
                .HasColumnType("jsonb");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<Guid>("CreatorId")
                .HasColumnType("uuid");

            b.Property<string>("Description")
                .HasColumnType("text");

            b.Property<DateTime?>("DownloadedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<DateTime?>("ExternalCreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<DateTime?>("ExternalUpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Extra")
                .HasColumnType("jsonb");

            b.Property<int>("FileCount")
                .HasColumnType("integer");

            b.Property<string>("GameSystem")
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<DateTime?>("LastScannedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("LicenseType")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)");

            b.Property<string>("Notes")
                .HasColumnType("text");

            b.Property<string[]>("PreviewImages")
                .IsRequired()
                .HasColumnType("text[]");

            b.Property<string>("PrintHistory")
                .HasColumnType("jsonb");

            b.Property<string>("PrintSettings")
                .HasColumnType("jsonb");

            b.Property<DateTime?>("PublishedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<int?>("Rating")
                .HasColumnType("integer");

            b.Property<string>("Scale")
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<string>("Source")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<Guid?>("SourceEntityId")
                .HasColumnType("uuid")
                .HasColumnName("source_entity_id");

            b.Property<string>("SourceId")
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<string>("SourceUrl")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)");

            b.Property<string>("ThumbnailPath")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)");

            b.Property<long>("TotalSizeBytes")
                .HasColumnType("bigint");

            b.Property<DateTime>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("AcquisitionMethod");

            b.HasIndex("BasePath")
                .IsUnique();

            b.HasIndex("Category")
                .HasFilter("category IS NOT NULL");

            b.HasIndex("CollectionName");

            b.HasIndex("CreatorId");

            b.HasIndex("Extra")
                .HasMethod("gin")
                .HasOperators("jsonb_path_ops");

            b.HasIndex("GameSystem")
                .HasFilter("game_system IS NOT NULL");

            b.HasIndex("LicenseType");

            b.HasIndex("Name")
                .HasMethod("gin")
                .HasOperators("gin_trgm_ops");

            b.HasIndex("Source");

            b.HasIndex("SourceEntityId");

            b.ToTable("models");
        });

        modelBuilder.Entity("Forgekeeper.Core.Models.ModelRelation", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasDefaultValueSql("gen_random_uuid()");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<Guid>("ModelId")
                .HasColumnType("uuid");

            b.Property<Guid>("RelatedModelId")
                .HasColumnType("uuid");

            b.Property<string>("RelationType")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.HasKey("Id");

            b.HasIndex("RelatedModelId");

            b.HasIndex("ModelId", "RelatedModelId", "RelationType")
                .IsUnique();

            b.ToTable("model_relations");
        });

        modelBuilder.Entity("Forgekeeper.Core.Models.ScanState", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasDefaultValueSql("gen_random_uuid()");

            b.Property<string>("DirectoryPath")
                .IsRequired()
                .HasMaxLength(2000)
                .HasColumnType("character varying(2000)");

            b.Property<int>("FileCount")
                .HasColumnType("integer");

            b.Property<DateTime>("LastModifiedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<DateTime>("LastScannedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("DirectoryPath")
                .IsUnique();

            b.ToTable("scan_states");
        });

        modelBuilder.Entity("Forgekeeper.Core.Models.Source", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasDefaultValueSql("gen_random_uuid()");

            b.Property<string>("AdapterType")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<bool>("AutoScan")
                .HasColumnType("boolean");

            b.Property<string>("BasePath")
                .IsRequired()
                .HasMaxLength(2000)
                .HasColumnType("character varying(2000)");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<string>("Slug")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            b.Property<DateTime>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("Slug")
                .IsUnique();

            b.ToTable("sources");
        });

        modelBuilder.Entity("Forgekeeper.Core.Models.Tag", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasDefaultValueSql("gen_random_uuid()");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<string>("Source")
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.HasKey("Id");

            b.HasIndex("Name")
                .IsUnique();

            b.ToTable("tags");
        });

        modelBuilder.Entity("Forgekeeper.Core.Models.Variant", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasDefaultValueSql("gen_random_uuid()");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("FileHash")
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<string>("FileName")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<string>("FilePath")
                .IsRequired()
                .HasMaxLength(2000)
                .HasColumnType("character varying(2000)");

            b.Property<long>("FileSizeBytes")
                .HasColumnType("bigint");

            b.Property<string>("FileType")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<Guid>("ModelId")
                .HasColumnType("uuid");

            b.Property<string>("PhysicalProperties")
                .HasColumnType("jsonb");

            b.Property<string>("ThumbnailPath")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)");

            b.Property<string>("VariantType")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.HasKey("Id");

            b.HasIndex("FilePath")
                .IsUnique();

            b.HasIndex("ModelId");

            b.ToTable("variants");
        });

        modelBuilder.Entity("model_tags", b =>
        {
            b.Property<Guid>("ModelId")
                .HasColumnType("uuid");

            b.Property<Guid>("TagId")
                .HasColumnType("uuid");

            b.HasKey("ModelId", "TagId");

            b.HasIndex("TagId");

            b.ToTable("model_tags");
        });

        modelBuilder.Entity("Forgekeeper.Core.Models.Model3D", b =>
        {
            b.HasOne("Forgekeeper.Core.Models.Creator", "Creator")
                .WithMany("Models")
                .HasForeignKey("CreatorId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("Forgekeeper.Core.Models.Source", "SourceEntity")
                .WithMany("Models")
                .HasForeignKey("SourceEntityId")
                .OnDelete(DeleteBehavior.SetNull);

            b.Navigation("Creator");
            b.Navigation("SourceEntity");
        });

        modelBuilder.Entity("Forgekeeper.Core.Models.ModelRelation", b =>
        {
            b.HasOne("Forgekeeper.Core.Models.Model3D", "Model")
                .WithMany("RelationsFrom")
                .HasForeignKey("ModelId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("Forgekeeper.Core.Models.Model3D", "RelatedModel")
                .WithMany("RelationsTo")
                .HasForeignKey("RelatedModelId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Model");
            b.Navigation("RelatedModel");
        });

        modelBuilder.Entity("Forgekeeper.Core.Models.Variant", b =>
        {
            b.HasOne("Forgekeeper.Core.Models.Model3D", "Model")
                .WithMany("Variants")
                .HasForeignKey("ModelId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Model");
        });

        modelBuilder.Entity("model_tags", b =>
        {
            b.HasOne("Forgekeeper.Core.Models.Model3D", null)
                .WithMany()
                .HasForeignKey("ModelId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("Forgekeeper.Core.Models.Tag", null)
                .WithMany()
                .HasForeignKey("TagId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Forgekeeper.Core.Models.Creator", b =>
        {
            b.Navigation("Models");
        });

        modelBuilder.Entity("Forgekeeper.Core.Models.Model3D", b =>
        {
            b.Navigation("RelationsFrom");
            b.Navigation("RelationsTo");
            b.Navigation("Variants");
        });

        modelBuilder.Entity("Forgekeeper.Core.Models.Source", b =>
        {
            b.Navigation("Models");
        });
#pragma warning restore 612, 618
    }
}
