// <auto-generated />
using System;
using System.Collections.Generic;
using Forgekeeper.Core.Models;
using Forgekeeper.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forgekeeper.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ForgeDbContext))]
    partial class ForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Forgekeeper.Core.Models.Creator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<int>("ModelCount")
                        .HasColumnType("integer")
                        .HasColumnName("model_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_creators");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_creators_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Name", "Source")
                        .IsUnique()
                        .HasDatabaseName("ix_creators_name_source");

                    b.ToTable("creators", (string)null);
                });

            modelBuilder.Entity("Forgekeeper.Core.Models.ImportQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence_score");

                    b.Property<string>("ConfirmedCreator")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("confirmed_creator");

                    b.Property<string>("ConfirmedModelName")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("confirmed_model_name");

                    b.Property<string>("ConfirmedSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("confirmed_source");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetectedCreator")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detected_creator");

                    b.Property<string>("DetectedModelName")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detected_model_name");

                    b.Property<string>("DetectedSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("detected_source");

                    b.Property<string>("DetectedVariantType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("detected_variant_type");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("original_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_import_queue");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_import_queue_status");

                    b.ToTable("import_queue", (string)null);
                });

            modelBuilder.Entity("Forgekeeper.Core.Models.Model3D", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AcquisitionMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("acquisition_method");

                    b.Property<string>("AcquisitionOrderId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("acquisition_order_id");

                    b.Property<string>("BasePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("base_path");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category");

                    b.Property<string>("CollectionName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("collection_name");

                    b.Property<List<ComponentInfo>>("Components")
                        .HasColumnType("jsonb")
                        .HasColumnName("components");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DownloadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("downloaded_at");

                    b.Property<DateTime?>("ExternalCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("external_created_at");

                    b.Property<DateTime?>("ExternalUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("external_updated_at");

                    b.Property<string>("Extra")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer")
                        .HasColumnName("file_count");

                    b.Property<string>("GameSystem")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("game_system");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scanned_at");

                    b.Property<string>("LicenseType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("license_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.PrimitiveCollection<List<string>>("PreviewImages")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("preview_images");

                    b.Property<List<PrintHistoryEntry>>("PrintHistory")
                        .HasColumnType("jsonb")
                        .HasColumnName("print_history");

                    b.Property<string>("PrintStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("print_status");

                    b.Property<PrintSettingsInfo>("PrintSettings")
                        .HasColumnType("jsonb")
                        .HasColumnName("print_settings");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Scale")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scale");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_entity_id");

                    b.Property<string>("SourceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_url");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("thumbnail_path");

                    b.Property<long>("TotalSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("total_size_bytes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_models");

                    b.HasIndex("AcquisitionMethod")
                        .HasDatabaseName("ix_models_acquisition_method");

                    b.HasIndex("BasePath")
                        .IsUnique()
                        .HasDatabaseName("ix_models_base_path");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_models_category")
                        .HasFilter("category IS NOT NULL");

                    b.HasIndex("CollectionName")
                        .HasDatabaseName("ix_models_collection_name");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_models_creator_id");

                    b.HasIndex("Extra")
                        .HasDatabaseName("ix_models_extra");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Extra"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Extra"), new[] { "jsonb_path_ops" });

                    b.HasIndex("GameSystem")
                        .HasDatabaseName("ix_models_game_system")
                        .HasFilter("game_system IS NOT NULL");

                    b.HasIndex("LicenseType")
                        .HasDatabaseName("ix_models_license_type");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_models_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Source")
                        .HasDatabaseName("ix_models_source");

                    b.HasIndex("SourceEntityId")
                        .HasDatabaseName("ix_models_source_entity_id");

                    b.ToTable("models", (string)null);
                });

            modelBuilder.Entity("Forgekeeper.Core.Models.ModelRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<Guid>("RelatedModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_model_id");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relation_type");

                    b.HasKey("Id")
                        .HasName("pk_model_relations");

                    b.HasIndex("RelatedModelId")
                        .HasDatabaseName("ix_model_relations_related_model_id");

                    b.HasIndex("ModelId", "RelatedModelId", "RelationType")
                        .IsUnique()
                        .HasDatabaseName("ix_model_relations_model_id_related_model_id_relation_type");

                    b.ToTable("model_relations", (string)null);
                });

            modelBuilder.Entity("Forgekeeper.Core.Models.PluginConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_encrypted");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("PluginSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plugin_slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_plugin_configs");

                    b.HasIndex("PluginSlug", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_plugin_configs_plugin_slug_key");

                    b.ToTable("plugin_configs", (string)null);
                });

            modelBuilder.Entity("Forgekeeper.Core.Models.ScanState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("DirectoryPath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("directory_path");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer")
                        .HasColumnName("file_count");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<DateTime>("LastScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scanned_at");

                    b.HasKey("Id")
                        .HasName("pk_scan_states");

                    b.HasIndex("DirectoryPath")
                        .IsUnique()
                        .HasDatabaseName("ix_scan_states_directory_path");

                    b.ToTable("scan_states", (string)null);
                });

            modelBuilder.Entity("Forgekeeper.Core.Models.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AdapterType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("adapter_type");

                    b.Property<bool>("AutoScan")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_scan");

                    b.Property<string>("BasePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("base_path");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sources");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_sources_slug");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("Forgekeeper.Core.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Forgekeeper.Core.Models.Variant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("file_hash");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<PhysicalProperties>("PhysicalProperties")
                        .HasColumnType("jsonb")
                        .HasColumnName("physical_properties");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("thumbnail_path");

                    b.Property<string>("VariantType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("variant_type");

                    b.HasKey("Id")
                        .HasName("pk_variants");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_variants_model_id");

                    b.HasIndex("ModelId", "FilePath")
                        .IsUnique()
                        .HasDatabaseName("ix_variants_model_id_file_path");

                    b.ToTable("variants", (string)null);
                });

            modelBuilder.Entity("Forgekeeper.Core.Models.SyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("BytesDownloaded")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_downloaded");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("FailedModels")
                        .HasColumnType("integer")
                        .HasColumnName("failed_models");

                    b.Property<int>("FilesDownloaded")
                        .HasColumnType("integer")
                        .HasColumnName("files_downloaded");

                    b.Property<string>("PluginSlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plugin_slug");

                    b.Property<int>("ScrapedModels")
                        .HasColumnType("integer")
                        .HasColumnName("scraped_models");

                    b.Property<int>("SkippedModels")
                        .HasColumnType("integer")
                        .HasColumnName("skipped_models");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TotalModels")
                        .HasColumnType("integer")
                        .HasColumnName("total_models");

                    b.HasKey("Id")
                        .HasName("pk_sync_runs");

                    b.HasIndex("PluginSlug")
                        .HasDatabaseName("ix_sync_runs_plugin_slug");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_sync_runs_started_at");

                    b.ToTable("sync_runs", (string)null);
                });

            modelBuilder.Entity("model_tags", b =>
                {
                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("ModelId", "TagId")
                        .HasName("pk_model_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_model_tags_tag_id");

                    b.ToTable("model_tags", (string)null);
                });

            modelBuilder.Entity("Forgekeeper.Core.Models.Model3D", b =>
                {
                    b.HasOne("Forgekeeper.Core.Models.Creator", "Creator")
                        .WithMany("Models")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_models_creators_creator_id");

                    b.HasOne("Forgekeeper.Core.Models.Source", "SourceEntity")
                        .WithMany("Models")
                        .HasForeignKey("SourceEntityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_models_sources_source_entity_id");

                    b.Navigation("Creator");

                    b.Navigation("SourceEntity");
                });

            modelBuilder.Entity("Forgekeeper.Core.Models.ModelRelation", b =>
                {
                    b.HasOne("Forgekeeper.Core.Models.Model3D", "Model")
                        .WithMany("RelationsFrom")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_model_relations_models_model_id");

                    b.HasOne("Forgekeeper.Core.Models.Model3D", "RelatedModel")
                        .WithMany("RelationsTo")
                        .HasForeignKey("RelatedModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_model_relations_models_related_model_id");

                    b.Navigation("Model");

                    b.Navigation("RelatedModel");
                });

            modelBuilder.Entity("Forgekeeper.Core.Models.Variant", b =>
                {
                    b.HasOne("Forgekeeper.Core.Models.Model3D", "Model")
                        .WithMany("Variants")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_variants_models_model_id");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("model_tags", b =>
                {
                    b.HasOne("Forgekeeper.Core.Models.Model3D", null)
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_model_tags_models_model_id");

                    b.HasOne("Forgekeeper.Core.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_model_tags_tags_tag_id");
                });

            modelBuilder.Entity("Forgekeeper.Core.Models.Creator", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Forgekeeper.Core.Models.Model3D", b =>
                {
                    b.Navigation("RelationsFrom");

                    b.Navigation("RelationsTo");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Forgekeeper.Core.Models.Source", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
