apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forgekeeper.fullname" . }}-secret
  labels:
    {{- include "forgekeeper.labels" . | nindent 4 }}
type: Opaque
stringData:
  encryption-key: {{ .Values.config.encryptionKey | quote }}
  {{- if and .Values.config.security.apiKey (ne .Values.config.security.apiKey "") }}
  api-key: {{ .Values.config.security.apiKey | quote }}
  {{- end }}
  {{- if .Values.postgresql.external.enabled }}
  connection-string: "Host={{ .Values.postgresql.external.host }};Port={{ .Values.postgresql.external.port }};Database={{ .Values.postgresql.external.database }};Username={{ .Values.postgresql.external.username }};Password={{ .Values.postgresql.external.password }}"
  {{- end }}
